<a href="https://colab.research.google.com/github/choki0715/lecture/blob/master/SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import numpy as np

A = np.random.randn(4, 3)
A

array([[-0.64455734,  1.99455504,  0.02989695],
       [ 0.01314807, -0.29221648, -1.20011377],
       [-0.32397004,  1.46019597,  0.41399839],
       [ 0.35031531,  1.62338575,  0.98832351]])

In [65]:
u, sig, v_t = np.linalg.svd(A, full_matrices=False)

print("u  :" + str(u.shape))
print("sig:" + str(sig.shape))
print("v_t:" + str(v_t.shape))

u  :(4, 3)
sig:(3,)
v_t:(3, 3)


In [66]:
sig

array([3.14750293, 1.36969623, 0.53009502])

In [67]:
s = np.diag(sig)
s

array([[3.14750293, 0.        , 0.        ],
       [0.        , 1.36969623, 0.        ],
       [0.        , 0.        , 0.53009502]])

In [68]:
tmp = np.matmul(u, s)
tmp

array([[ 1.95092113, -0.75361185, -0.14343542],
       [-0.67393386, -0.97734757,  0.34123493],
       [ 1.54166428, -0.14831668, -0.09897948],
       [ 1.80824939,  0.57526589,  0.36631789]])

In [70]:
AA = np.matmul(tmp, v_t)
AA

array([[-0.64455734,  1.99455504,  0.02989695],
       [ 0.01314807, -0.29221648, -1.20011377],
       [-0.32397004,  1.46019597,  0.41399839],
       [ 0.35031531,  1.62338575,  0.98832351]])

In [71]:
A_t = np.transpose(A)
A_t



array([[-0.64455734,  0.01314807, -0.32397004,  0.35031531],
       [ 1.99455504, -0.29221648,  1.46019597,  1.62338575],
       [ 0.02989695, -1.20011377,  0.41399839,  0.98832351]])

In [72]:

AA_t = np.matmul(A, A_t)
A_tA = np.matmul(A_t, A)

print(AA_t)
print(A_tA)

[[ 4.3945978  -0.62719628  3.13363578  3.04168179]
 [-0.62719628  1.5258364  -0.92779807 -1.65587475]
 [ 3.13363578 -0.92779807  2.40852351  2.666134  ]
 [ 3.04168179 -1.65587475  2.666134    3.73488548]]
[[ 0.64330444 -1.19381003  0.17705231]
 [-1.19381003  8.83119385  2.6192732 ]
 [ 0.17705231  2.6192732   2.5893449 ]]


In [73]:
u_eig, u_vec = np.linalg.eig(AA_t)
u_eig, u_vec

(array([9.90677469e+00, 1.87606777e+00, 2.70970805e-16, 2.81000729e-01]),
 array([[ 0.6198314 , -0.55020364, -0.48976433, -0.27058436],
        [-0.21411699, -0.7135506 ,  0.17498219,  0.64372408],
        [ 0.48980551, -0.10828436,  0.84468965, -0.18672026],
        [ 0.57450284,  0.41999523, -0.12653666,  0.69104194]]))

In [74]:
v_eig, v_vec = np.linalg.eig(A_tA)
v_eig, v_vec

(array([9.90677469, 0.28100073, 1.87606777]),
 array([[-0.11429926,  0.91577018,  0.38509825],
        [ 0.93620504,  0.22897268, -0.26663014],
        [ 0.33234891, -0.3300553 ,  0.88352006]]))

In [75]:
from sklearn.decomposition import TruncatedSVD

my_svd = TruncatedSVD(n_components=2)

my_svd.fit(A)

TruncatedSVD()

In [76]:
print(my_svd.singular_values_)

[3.14750293 1.36969623]


In [77]:
A_2 = my_svd.transform(A)
A_2

array([[ 1.95092113,  0.75361185],
       [-0.67393386,  0.97734757],
       [ 1.54166428,  0.14831668],
       [ 1.80824939, -0.57526589]])

In [78]:
print( s[:2,:2] )
A_2 = np.matmul(A_2, s[:2,:2])
A_2 = np.matmul( A_2, v_t[:2,:])
A_2

[[3.14750293 0.        ]
 [0.         1.36969623]]


array([[-0.3043522 ,  5.47357434,  2.95278492],
       [ 0.75797181, -2.34281596,  0.47775973],
       [-0.47639268,  4.48866903,  1.79217351],
       [-0.95396499,  5.53847156,  1.19539357]])

In [79]:
 from sklearn.datasets import load_iris
 from sklearn.decomposition import TruncatedSVD 

In [80]:
 iris = load_iris()
 X = iris.data
 Y = iris.target
 X[:10] 

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [81]:
SVD_2=TruncatedSVD(2)

In [82]:
 X_truncated = SVD_2.fit_transform(X)
 X_truncated[:10] 

array([[5.91274714, 2.30203322],
       [5.57248242, 1.97182599],
       [5.44697714, 2.09520636],
       [5.43645948, 1.87038151],
       [5.87564494, 2.32829018],
       [6.47759822, 2.32464996],
       [5.5159752 , 2.07090423],
       [5.85092859, 2.14807482],
       [5.15891972, 1.77506408],
       [5.64500117, 1.99000106]])